### ISSUE TITLE
broken images on /campaigns

### ISSUE THREAD

**Issue by mikefantini** [DoSomething/tower#44]
on https://www.dosomething.org/campaigns "LGBT HBD", "Headhunters", and "Pineapple Push-Ups" have broken images even though new images exist on campaign page

on non-AWS webhead only Headhunters was broken

![image](https://cloud.githubusercontent.com/assets/6330971/7777363/5e480ffa-0090-11e5-99f3-6e08a7859c59.png)

**Comment by sergii-tkachenko** [comment]
@sheydari-ds Maybe this images were added after you mirrored shared files?

**Comment by sheydari-ds** [comment]
Taking a look.

**Comment by sheydari-ds** [comment]
@sergii-tkachenko Rsync mirror is perpetually on-going (delayed by 20 minutes or so). I think part of this is the Akamai server not reading the right origin traffic from the old server, but taking a closer look.

**Comment by sergii-tkachenko** [comment]
Actually, I can't see Headhunter image on old server as well.

**Comment by sergii-tkachenko** [comment]
LGBT HBD pic has link to different images on the Rackspace and AWS:
- Rackspace: https://dosomething-a.akamaihd.net/sites/default/files/styles/300x300/public/images/LGBTHBD_hero_square_0.jpg?itok=d-ssp6XL
- https://dosomething-a.akamaihd.net/sites/default/files/styles/300x300/public/images/LGBTParty_hero_square.jpg?itok=EPHRwWSE

**Comment by sergii-tkachenko** [comment]
So this must be DB sync

**Comment by sheydari-ds** [comment]
Yeah.

**Comment by sheydari-ds** [comment]
@mikefantini I think this was fixed. Please confirm, and feel free to close out this ticket.

**Comment by mikefantini** [comment]
yup fixed!
