### ISSUE TITLE
permalink is sharing other user's image

### ISSUE THREAD

**Issue by mikefantini** [DoSomething/tower#46]
when sharing from https://www.dosomething.org/reportback/80947?fid=110809 a different user's image is the one that's actually getting shared on social

![image](https://cloud.githubusercontent.com/assets/6330971/7777960/268c52ce-0095-11e5-955c-d70bc5b68159.png)

**Comment by sergii-tkachenko** [comment]
@sheydari-ds I suspect this is because ids are not sync back from RDS to Rackspace?

**Comment by sergii-tkachenko** [comment]
So facebook looks for image with same id as @mikefantini created, but on old server so it gets the one with same id but uploaded by somebody else.

**Comment by sheydari-ds** [comment]
Hmm, this one is an interesting one. RDS is live syncing from Prod. Checking on the sync status now, making sure nothing is broken.

**Comment by sergii-tkachenko** [comment]
Yes, so thing was that Facebook retrieved this image from the old server from the resource with same id as @mikefantini's.
URL: https://www.dosomething.org/reportback/80947?fid=110809

Old server:
![image](https://cloud.githubusercontent.com/assets/672669/7778804/a68ada62-00d7-11e5-83e0-7a951a01ae95.png)

New server:
![image](https://cloud.githubusercontent.com/assets/672669/7778833/e76aca06-00d7-11e5-90b1-ad38a282918f.png)

**Comment by sergii-tkachenko** [comment]
@sheydari-ds Yes, RDS is syncing data from Rackspace, Rackspace prod isn't syncing data from RDS.
So @mikefantini created new record in RDS and after that user `saharra` created new record in Rackspace. Autoincrement and bim-bam-bum we have 2 records with same id.

**Comment by sergii-tkachenko** [comment]
I think the best thing to do would be reimport Rackspace to RDS and resync images from Rackspace to RDS during the maintenance window on May 26th.

**Comment by sheydari-ds** [comment]
yeah, we now have duplicate entries reported on the slave. :) I'm going to dump the db and re-import it now that testing is done.

**Comment by sheydari-ds** [comment]
Until we just did testing the RDS replication was running fine. I'd prefer we have as little to do during downtime as possible. Unless you have further testing to do, I'm going to re-enable the rsync and RDS slave sync from the top, and then we can leave them alone till migration day.

**Comment by sergii-tkachenko** [comment]
Yes. Mike finished also:
> Mike Fantini: pretty much all set with core member experiences, testing some admin experiences now
> Mike Fantini: all set on aws testing fyi

I think we can close this now.

**Comment by sheydari-ds** [comment]
Yes.
