### ISSUE TITLE
tumblr dialogue never opens up on permalink

### ISSUE THREAD

**Issue by mikefantini** [DoSomething/tower#47]
happened previously on non-AWS servers: https://github.com/DoSomething/dosomething/issues/4337

![image](https://cloud.githubusercontent.com/assets/6330971/7778078/18438e84-0096-11e5-9034-624da46f5b17.png)

**Comment by sergii-tkachenko** [comment]
This is actually a consequence of #45. Closing it as a duplicate.

**Comment by mikefantini** [comment]
@sergii-tkachenko are you sure? FB and twitter dialogue boxes open as expected
